# Generated by Django 4.1.5 on 2023-01-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
        ('core', '0025_pumping_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='feeding_target',
            field=models.PositiveIntegerField(null=True, verbose_name='Daily feeding target'),
        ),
    ]
